version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: studyleague-db
    environment:
      MYSQL_ROOT_PASSWORD: Rakesh@123
      MYSQL_DATABASE: studyleague
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: .
    container_name: studyleague-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://studyleague-db:3306/studyleague?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rakesh@123
      SPRING_MAIL_USERNAME: rakeshreddy251507@gmail.com
      SPRING_MAIL_PASSWORD: 1234567
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
