version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: studyleague-db
    environment:
      MYSQL_ROOT_PASSWORD: Rakesh@123      # Root password
      MYSQL_DATABASE: studyleague          # Your database name
      MYSQL_USER: root                     # MySQL user
      MYSQL_PASSWORD: Rakesh@123           # Password for the user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    build: .
    container_name: studyleague-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: studyleague
      MYSQL_USER: root
      MYSQL_PASSWORD: Rakesh@123
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db_data:
